config/routes.rb
Rails.application.routes.draw do

  
  root 'home#new'
  
  resources :home

  get 'sessions/new'

  get 'register' => 'users#new'

  get    'login'   => 'sessions#new'

  post   'login'   => 'sessions#create'
  
  delete 'logout'  => 'sessions#destroy'

  match '/auth/:provider/callback' => 'users#facebook',via: [:get, :post]
  
  resources :users do
    member do
      get :following, :followers
    end
  end

 resources :relationships,       only: [:create, :destroy]

  resources :albums
 

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user

  has_many :images ,dependent: :destroy

  accepts_nested_attributes_for :images,:allow_destroy => true 

  validates :user_id, presence: true
  validates :album_name, presence: true
  validates :visibility, presence: true


  
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :album

  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  

  belongs_to :follower, class_name: "User"

  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base


	#validation of model
	 extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  
	validates :username, presence: true

	Regular_Expr = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: Regular_Expr }

	has_secure_password


  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

 has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
 has_many :following, through: :active_relationships,  source: :followed
 has_many :followers, through: :passive_relationships, source: :follower

 has_many :albums,dependent: :destroy

#images
  
 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/




def slug_candidates
    [
      :username,
      [:username, :id]
    ]
  end
  
  def to_param
   username.parameterize
  end



# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end




#facebook login
 	def self.from_omniauth(auth)
  	
		user=User.where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
    	user.username=auth.info.name
    	user.email=auth.info.email
    	user.location=auth.info.location
      user.avatar=process_uri(auth.info.image)

    	user.password_digest=User.digest("Password")
      end
      user.save!

      return user
	end

def self.process_uri(uri)
   avatar_url = URI.parse(uri)
   avatar_url.scheme = 'https'
   avatar_url.to_s
end


  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

	 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	def index
		@album=Album.where(:user_id => current_user[:id])
	end



	def new
		@album=Album.new
		@album.images.build
	
  	end
	
	def create 
	 	 @album = current_user.albums.build(albums_params)
	     if @album.save
    		    flash[:success] = "album created!"
      		    redirect_to albums_path    			
    	end

	end
	
	def show
		@images=Image.where(:album_id => params[:id])		
	end
	
	def destory
	
	end


  private

    def albums_params
      params.require(:album).permit(:album_name,:visibility,images_attributes: [:avatar, :_destroy])
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include HomeHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def new
			@q = User.ransack(params[:q])
	end

	def index
		@q = User.ransack(params[:q])
		@user = @q.result
	end

	def show
			#user=User.find(:all,:conditions => ["username = ?",params[:home][:username]])
			#@user=User.all(:conditions =>["username = :username ", { :username => params[:home][:username]}])
			#@user=User.all(:conditions => ["username = ?",params[:home][:username]])	
			#@user=User.where("username LIKE ? OR email = ? OR location = ?", params[:home][:search], params[:home][:search], params[:home][:search])
			#@user = User.find_by(username: params[:home][:username])
			

		
		@user=User.friendly.find(params[:id])

		@album=Album.where(:user_id => @user.id,:visibility => "public")


	
      @friend =@user.following


      @friend_album=Album.where(:user_id => @user.following,:visibility => "friend")

	end




end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to home_path(user)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to home_path(user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     	log_in user
        current_user
      redirect_to user
    else
    	
    	flash.now[:danger] = 'Invalid email/password combination'
    	render 'new'
    end	
	  
  end
  
  def destroy
  	 log_out
     redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user=User.new
  
  end

  def show
     @user = User.friendly.find(params[:id])
    


  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      current_user
      flash[:success] = "Welcome to the My App!"
      redirect_to @user
      
    else
      render 'new'
    end
  end

  def edit 
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
          flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
  end

  def index
    @user=User.all
  end

  def facebook
     @user=User.from_omniauth(request.env["omniauth.auth"])
          
    if @user.persisted?
      redirect_to @user
    else
       redirect_to register_path
    end
  end



  private

    def user_params
      params.require(:user).permit(:username, :email,:location, :password,
                                   :password_confirmation,:avatar)
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	
	
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
    	session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
   	  @current_user ||= User.friendly.find_by(id: session[:user_id])
  end

   	# Returns true if the user is logged in, false otherwise.
 	def logged_in?
    	!current_user.nil?
 	end

 	def log_out
    	session.delete(:user_id)
   		@current_user = nil
 	end
  def current_user?(user)
      user == current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
 <h1>All Albums</h1>
        	<%= link_to 'Add new Albums',new_album_path %>
 <br/><br/>
<% if @album.count != 0 %>
	<%= @album.each do |u| %>
		<%= u.album_name %>

        	<%= link_to 'view',album_path(u.id) %>
        
		 <br/><br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/albums/new.html.erb
<h1>Albums </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= nested_form_for  @album ,:url => albums_path, :html => { :multipart => true }  do |f| %>
    
  <%= render 'shared/error_message', object: f.object %>

      <%= f.label :album_name %>
      <%= f.text_field :album_name , class: 'form-control'%>

      <%= f.label :visibility %>  
      <%= f.select :visibility, options_for_select([ "public","private","friend" ]),class: 'form-control'%>

      <%= f.fields_for :images do |u| %>
          <%= f.label "Profile" %>
          <%= u.file_field :avatar %>  
        <%= u.link_to_remove "Remove this image" %>
      <% end %>
       <p><%= f.link_to_add "Add a task", :images %></p>

      <%= f.submit "Create", class: "btn btn-primary" %>
     <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<h1>All Images</h1>
        	
 <br/><br/>
<% if @images.count != 0 %>
	<%= @images.each do |a| %>

		<%= image_tag a.avatar ,:size => "80x80" %>
        
	<br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/home/index.html.erb
<h1>All users</h1>
<% if @user.count != 0 %>
	<%= @user.each do |u| %>

		 
				<%= u.username %>
		    	 <%= u.email %>
			
        		<%= link_to 'view',home_path(u.username) %>
         <br/><br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/home/new.html.erb
<h1>Search</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= search_form_for @q , url: home_index_path do |f| %>

     
  <%= f.search_field :username_or_email_or_location_cont, placeholder: "Username Email Location",class: 'form-control' %>

  <%= f.submit  "Search", class: "btn btn-primary" %>
    <% end %>
    <a href="/auth/facebook">Login Via facebook</a>
    <p>New User  <%= link_to "Registation!", register_path %></p>
  </div>
</div>

app/views/home/show.html.erb
 <% if logged_in? %>
  		 <%= image_tag @user.avatar ,:size => "80x80" %>
  <% end %>
<%= @user.username %>
 <%= @user.email %>
 <%= @user.location %>
 <% if logged_in? %>
  		
  		<section class="stats">

        <%= render 'shared/stats' %>
 	<%= render 'shared/follow_form'  %>
        Albums List<br/><br/>

        <% if @album.count != 0 %>
		<%= @album.each do |u| %>
			<%= u.album_name %>

        		<%= link_to 'view',album_path(u.id) %>
        
			 <br/><br/><br/>
 		<% end %>
		<% else %>
				Sorry ,no such records exists
		<% end %>


 </section>
<br/>
 friend list
 <br/><br/>

	<% if @friend.count != 0 %>
			<%= @friend.each do |u| %>
			<%= u.username %>
			 <br/><br/><br/>
 		<% end %>
	<% else %>
				Sorry ,no such records exists
	<% end %>
<br/><br/>
friend list albums(visibility =friend)
<br/><br/> 
	<% if @friend_album.count != 0 %>
			<%= @friend_album.each do |u| %>
			<%= u.album_name %>

        		<%= link_to 'view',album_path(u.id) %>
			 <br/><br/><br/>
 		<% end %>
	<% else %>
				Sorry ,no such records exists
	<% end %>

  <% end %>
 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "Albums", albums_path %></li>
         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>application</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Update profile </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_message', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :location %>
      <%= f.text_field :location %>

      <%= f.label "Profile" %>
      <%= f.file_field :avatar %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>

      <a href="/auth/facebook">Login Via facebook</a>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
<% if @user.count != 0 %>
	<%= @user.each do |u| %>
		<%= u.username %>
		 <%= u.email %>
			
        	<%= link_to 'view',home_path(u.username) %>
        
		 <br/><br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/users/new.html.erb
<h1>Registation</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :html => { :multipart => true } do |f| %>
      <%= render 'shared/error_message', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username , class: 'form-control'%>

      <%= f.label :email %>
      <%= f.text_field :email , class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location , class: 'form-control'%>

      <%= f.label "Profile" %>
      <%= f.file_field :avatar %>

      <%= f.label :password %>
      <%= f.password_field :password , class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation , class: 'form-control'%>

      <%= f.submit "Submit", class: "btn btn-primary" %>

      <a href="/auth/facebook">Login Via facebook</a>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
 

 <%= image_tag @user.avatar ,:size => "80x80" %> <%= @user.username %>, <%= @user.email %>
  <section class="stats">
        <%= render 'shared/stats' %>
 </section>

 <%= render 'shared/follow_form'  %>